### ISSUE TITLE
Fixed navbar

### ISSUE THREAD

**Issue by ancyp** [systers/systers.github.io#119] opened 2018-03-03 17:11 UTC
## Description
As a user of the website, I'd like to be able to access the header even when I reach the bottom of the page. A fixed navbar or "Go to Top" link would help.

### Update [Required]
- [ ]  index.html
- [ ] code-of-conduct.html
- [ ] contactus.html
- [ ]  gsoc/2009.html
- [ ] gsoc/2010.html
- [ ] gsoc/20111.html
- [ ] gsoc/2012.html
- [ ] gsoc/2013.html
- [ ] gsoc/2014.html
- [ ] gsoc/2015.html
- [ ] gsoc/2016.html
- [ ] gsoc/2017.html
- [ ] member-levels.html
- [ ] newcomers.html
- [ ] open-source-workflow.html
- [ ] Outreachy/2017.html
- [ ] reporting-guidelines.html
- [ ] RGSoC/2018.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by Saichethan** [comment] 2018-03-03 18:48
@ancyp  actually if u have joined slack (I don't know if you are) in gh-pages thread there are some specifications for new website that is to be build please check that link, this is included if I am not wrong

**Comment by divyanshu-rawat** [comment] 2018-03-06 00:00
@sara-02 what are your thought on this issue?

**Comment by devshiva619** [comment] 2018-05-19 16:20
@ancyp hey I a beginner and would like to work on this issue, but need bit of clarification regarding the issue.

**Comment by ancyp** [comment] 2018-05-20 16:34
@divyanshu-rawat @BaaniLeen aren't we doing a fixed navbar  in GSoC?

**Comment by devshiva619** [comment] 2018-05-22 08:34
@ancyp Please let me know if I can work on.

**Comment by SubbulakshmiRS** [comment] 2018-07-13 17:14
@ancyp unless the issue is taken , can I please be assigned to this issue ?

**Comment by BaaniLeen** [comment] 2018-07-13 17:20
@SubbulakshmiRS This issue is fixed. Feel free to take any other issue. :)

**Closed** 2018-07-13 17:20 UTC
Labels: Category: User Interface, Difficulty: EASY, First Timers Only, Type: Enhancement
