### ISSUE TITLE
Add a newline at the end of each file

### ISSUE THREAD

**Issue by BaaniLeen** [systers/systers.github.io#226] opened 2018-06-29 01:10 UTC
## Description
As a contributor,
I need add a newline at the end of each file in the gsoc18-code branch,
so that I can remove the tslint warning for the same.

### Update [Required]
- [ ] All files

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by shreyateeza** [comment] 2018-07-09 05:34
@BaaniLeen Can I work on this issue?

**Comment by BaaniLeen** [comment] 2018-07-09 06:03
@shreyateeza Just a suggestion, since this is a First Timers only issue and you are already a contributor, I would suggest you to work on other bugs and features, after getting them assigned :)

**Comment by shreyateeza** [comment] 2018-07-09 06:19
Alright @BaaniLeen ! Thank you.

**Comment by SubbulakshmiRS** [comment] 2018-07-14 12:00
Can i be assigned to this issue ? @BaaniLeen

**Comment by BaaniLeen** [comment] 2018-07-14 12:05
Sure @SubbulakshmiRS ! :)
According to the Systers Guidelines, you should only start working on an issue after the maintainers assign the issue to you (I can't assign you the same!).
@systers/maintainers-gh-pages Can you please assign the issue to Subbulakshmi so that she can work on it? Thanks! :)

**Comment by Janiceilene** [comment] 2018-07-14 18:39
@SubbulakshmiRS I'll get you officially assigned as soon as @ExactlyMay gets you into the Newcomers team, but the issue is yours and you can begin working on it!

**Comment by aakankshadhurandhar** [comment] 2018-07-15 04:50
@BaaniLeen can I work on this isue

**Comment by BaaniLeen** [comment] 2018-07-15 04:55
@aakankshadhurandhar This issue is being worked upon by @SubbulakshmiRS .
Let me know if you are interested to work on Issue #237 or #241 .
Else, Will try to create new newcomer issues and ping you there :)

**Comment by BaaniLeen** [comment] 2018-07-15 05:08
Issue #243 is also a newcomer friendly issue and is available to be assigned.

**Comment by SubbulakshmiRS** [comment] 2018-07-17 04:52
where is the folder for gsoc-2018 ? I was only able to find some html files in gsoc (not for 2018) or rgsoc 2018 html file .Can I please be directed to the folder ? @BaaniLeen

**Comment by BaaniLeen** [comment] 2018-07-17 10:41
Hey,
You need to contribute to the gsoc18-code branch. Feel free to ask on slack for any issues you are facing in doing the same, in the #gh-pages channel :)

**Closed** 2018-07-24 04:53 UTC
Labels: Category: Quality Assurance, Difficulty: EASY, First Timers Only, Priority: LOW, Status: Available
