### ISSUE TITLE
Issue While Contributing To The Repo.

### ISSUE THREAD

**Issue by divyanshu-rawat** [systers/systers.github.io#91] opened 2018-02-26 10:58 UTC
## Description
A discussion is already going on this issue in slack https://systers-opensource.slack.com/ #question  channel.
Strange behavior while rebasing the repository 

## Mocks
I haven't made any changes in the CODE_OF_CONDUCT and when I am trying to rebase it shows unstaged changes.

![screen shot 2018-02-26 at 11 39 35 am](https://user-images.githubusercontent.com/13464678/36666529-40c64410-1aeb-11e8-92e5-e22f698f8bb0.png)

Let me summarize it again after following these set of commands.
```
git remote add upstream https://github.com/systers/systers.github.io
git fetch upstream
git checkout master
git rebase upstream/master

```

![screen shot 2018-02-26 at 11 41 07 am](https://user-images.githubusercontent.com/13464678/36666560-594546a8-1aeb-11e8-8ea9-96d21ddac726.png)

The concern is even if I keep CODE_OF_CONDUCT.md untouched it still shows it is modified when I do `git status` as depicted in the above-mentioned screenshot.

> For More information on this please visit systers open source slack https://systers-opensource.slack.com/ #questions channel.

As a user,
I can figure out how to resolve this problem.
So, that another user will not face the same problem in the future.

### Update [Required]
- [ ] Reason for the strange behavior is still a mystery.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
Don't Know

**Comment by shreyateeza** [comment] 2018-02-26 11:08
@divyanshu-rawat Actually it should be followed like this -

1. `git remote add upstream https://github.com/systers/systers.github.io`
2. `git fetch upstream`
3. `git rebase upstream/master`
4. `git checkout master`

This won't result in any error. I myself had followed it.
The key rule is **First rebase, then Checkout**
I request you to try it yourself. If any error comes, then please let me know.
:wink:

**Comment by shreyateeza** [comment] 2018-02-26 11:10
@MeepyMay @prachi1210 @sara-02 Please correct me if I am wrong.

**Comment by divyanshu-rawat** [comment] 2018-02-26 11:15
@shreyateeza by following your guidelines 👍 

![screen shot 2018-02-26 at 12 12 54 pm](https://user-images.githubusercontent.com/13464678/36667529-701be366-1aee-11e8-994f-10082f2a6f43.png)

The issue is with CODE_OF_CONDUCT.md please read the description mentioned in mock carefully.
Even if I will try to git add CODE_OF_CONDUCT.md then still it is not adding to the staging area it is still unstaged.

See below-mentioned screenshot :) 
![screen shot 2018-02-26 at 12 15 19 pm](https://user-images.githubusercontent.com/13464678/36667618-c264ed20-1aee-11e8-9b3c-e7209fd85e5f.png)

**Comment by simsausaurabh** [comment] 2018-02-26 11:29
You are on which branch at initial before following these commands? @divyanshu-rawat 
Always be on ```master``` branch while doing ```fetch``` and ```rebase``` then if you want do: ```git checkout -b new-branch``` this will create the copy of your master branch. And obviously you can't rebase with unstaged changes.

You can do:
```
git add .
git stash
```
for removing the changes which it is showing. Feel free to ask if you face this again, since I am unable to reproduce this issue. Thanks.

**Comment by shreyateeza** [comment] 2018-02-26 11:39
Yes I totally agree with @simsausaurabh. Even when I tried to do what you did @divyanshu-rawat , I get the same error. Look at the following screenshot - 
![checking](https://user-images.githubusercontent.com/30488330/36668516-9445ff32-1b17-11e8-8741-d04a04315072.png)

Please first follow the steps in the order I have written, then tell me if you get any error.

**Comment by divyanshu-rawat** [comment] 2018-02-26 11:45
@simsausaurabh  @shreyateeza I am on the master branch while doing fetch and rebase and I haven't created any new branch at all and @simsausaurabh after following your instructions it still the same although I already tried everything before even you can see it in the slack channel as well slack https://systers-opensource.slack.com/ #question channel.

![screen shot 2018-02-26 at 12 42 46 pm](https://user-images.githubusercontent.com/13464678/36668839-db6aeef6-1af2-11e8-9100-ba42abb41a50.png)

**Comment by simsausaurabh** [comment] 2018-02-26 11:49
Have you opened the project in any text editor or IDE while installing the project on command line? Or while following the instructions?

**Comment by divyanshu-rawat** [comment] 2018-02-26 11:50
@shreyateeza @simsausaurabh Now I have followed almost everything just see this attached snapshot but nothing is working at all 
![screen shot 2018-02-26 at 12 46 59 pm](https://user-images.githubusercontent.com/13464678/36668934-38892d00-1af3-11e8-81dd-4a9cc622817c.png)

Although I figured out the solution for the same would you guys try to find it yourself or you want me to reveal it ;)

**Comment by simsausaurabh** [comment] 2018-02-26 11:51
Did you set the upstream?

**Comment by divyanshu-rawat** [comment] 2018-02-26 11:51
@simsausaurabh I am using sublime text for the same and have followed instructions even @shreyateeza is facing the same problem :) 

Snapshot of text editor is attached 
![screen shot 2018-02-26 at 12 50 57 pm](https://user-images.githubusercontent.com/13464678/36669042-bb99669c-1af3-11e8-93a8-0b07dc991de8.png)

**Comment by divyanshu-rawat** [comment] 2018-02-26 11:51
@simsausaurabh upstream is not an issue it's fairly weird issue ;)

**Comment by simsausaurabh** [comment] 2018-02-26 11:53
Can you please provide snapshot for ```git remote -v```.

**Comment by divyanshu-rawat** [comment] 2018-02-26 11:54
ya sure 
![screen shot 2018-02-26 at 12 54 13 pm](https://user-images.githubusercontent.com/13464678/36669142-2cc8ff3a-1af4-11e8-8fa5-d96aac550fc7.png)

**Comment by simsausaurabh** [comment] 2018-02-26 11:56
I am not getting why are you checking out master, when you are already on it. Please move this discussion on slack. Thanks.

**Comment by divyanshu-rawat** [comment] 2018-02-26 11:59
ya thanks, @simsausaurabh it's already on slack and another thing is that I know it's I am already in master it's a dumb thing to checking it out again to master but is not related to this issue at all :)

**Comment by shreyateeza** [comment] 2018-02-26 12:05
As you now know the cause of this error, you are requested to close this issue. @divyanshu-rawat

**Comment by divyanshu-rawat** [comment] 2018-02-26 12:26
Ya, but how the community will know how to resolve this?

**Comment by sara-02** [comment] 2018-02-27 06:31
@divyanshu-rawat For the time being I will let this issue be, because other might face it well.
Also can you comment with the steps that can help overcome this problem @shreyateeza please add your comments as well, with the steps you took to overcome this issue.

**Comment by divyanshu-rawat** [comment] 2018-03-02 10:14
That's basically an issue with the caching please find attached a snapshot of the terminal to get more insights about this.
I hope it helps everyone when they will encounter this kind of problem.

![cached](https://user-images.githubusercontent.com/13464678/36894092-a972b62a-1e0a-11e8-92d7-c75c88670c79.png)

**Comment by divyanshu-rawat** [comment] 2018-03-02 10:15
@shreyateeza @sara-02 @MeepyMay @prachi1210 @simsausaurabh  Above I have explained the solution to the problem now you guys can close this issues. 👍

**Comment by shreyateeza** [comment] 2018-03-02 10:19
@divyanshu-rawat Cool!
@sara-02 I apologise for not providing the solution. Actually I have semester exams going on.

**Comment by MeepyMay** [comment] 2018-03-12 23:06
Closing. Thank you for working it through @divyanshu-rawat. Please help any students who are struggling. 

We used Glitch when developing version 1.0, so it may have caused a few bugs.

**Closed by MeepyMay** 2018-03-12 23:06 UTC

**Comment by divyanshu-rawat** [comment] 2018-03-12 23:07
@MeepyMay I will help surely help any student who is struggling with this 👍
