### ISSUE TITLE
Fix broken link

### ISSUE THREAD

**Issue by adityac8** [systers/systers.github.io#166] opened 2018-03-31 13:14 UTC
## Description
As a USER,
I need fix a broken link,
so that I can make the website more interactive & responsive.

## Mocks
![image](https://user-images.githubusercontent.com/19192257/38163609-90dcc86e-3514-11e8-9d40-c9b83a2e0ac9.png)
Current Link
- http://localhost:8001/index.html/#programs

Required Link
-  http://systers.io/#programs

### Update [Required]
- [ ] http://systers.io/member-levels
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5-10 min

**Comment by BaaniLeen** [comment] 2018-03-31 13:19
@adityac8 The link http://systers.io/#programs works perfectly fine. Does it not work in the local version? Kindly provide the mockscreens for the same :)
Also, for the Update part, you need to mention the files which shall be updated to solve the given issue, so please update that too! :)

**Comment by adityac8** [comment] 2018-03-31 13:24
@BaaniLeen I have updated the issue and added the mockup. I agree that the link http://systers.io/#programs works. But the link given on  http://systers.io/member-levels is broken.

**Comment by adityac8** [comment] 2018-03-31 13:34
Hey @sara-02 @MeepyMay May I work on this issue?

**Comment by divyanshu-rawat** [comment] 2018-03-31 17:45
@adityac8 it's duplicate of #136.

**Comment by adityac8** [comment] 2018-03-31 19:29
Hey @divyanshu-rawat I didn't see that as I searched through the open bugs. Looks that you have generated a PR for that!! Nice to see how you have documented the issue. 👍  I would keep looking for any other bugs and generate a new issue for them 😃 Thanks for the response.

**Comment by divyanshu-rawat** [comment] 2018-03-31 19:30
@adityac8 Thanks 👍

**Comment by sara-02** [comment] 2018-04-02 06:38
@divyanshu-rawat @adityac8 If this is duplicate issue then can we close this one?

**Comment by Tharangi** [comment] 2018-04-18 15:56
Yes @sara-02. Let's close this since this a duplicate of #136 .

**Closed by Tharangi** 2018-04-18 15:56 UTC

**Comment by divyanshu-rawat** [comment] 2018-04-18 16:37
@Tharangi 👍
