### ISSUE TITLE
Member Levels > Other Participation Options > Mentor: "programs" has a link to localhost

### ISSUE THREAD

**Issue by isabelcosta** [systers/systers.github.io#159] opened 2018-03-23 20:51 UTC
## Description
In the page [member-levels](http://systers.io/member-levels) of the website systers.io, under the section "Other Participation Options", the link for the word programs in the sentence "(...) various programs Systers participates in (...)" has a link to localhost. The following link: http://localhost:8001/index.html/#programs

## Mocks

Section of the page with the wrong link:

![image](https://user-images.githubusercontent.com/11148726/37852669-5b502af4-2edb-11e8-8039-5148e80f41fd.png)

### Update

- [ ] [member-levels.html](https://github.com/systers/systers.github.io/blob/master/member-levels.html) file has the localhost link

## Definition of Done
- [ ] The link for the mentor programs has a proper link to Systers' programs

## Estimation
5 minutes

**Comment by isabelcosta** [comment] 2018-03-23 20:56
Can I fix this issue?

**Comment by sara-02** [comment] 2018-03-24 03:39
@isabelcosta Thanks for reporting it in a structured format, but this seems to be a duplicate of https://github.com/systers/systers.github.io/pull/137

**Comment by divyanshu-rawat** [comment] 2018-03-24 08:36
@sara-02 it's duplicate one of #137 👍

**Comment by isabelcosta** [comment] 2018-03-24 18:26
@sara-02 @divyanshu-rawat I searched in the issues for the possibility of duplicate issues, but I didn't find that one. Sorry for creating an unnecessary issue. Glad the bug is being taken cared of :)

**Closed** 2018-03-25 14:44 UTC
