### ISSUE TITLE
The horizontal scrollbar is not required

### ISSUE THREAD

**Issue by Jap-Leen** [systers/systers.github.io#66] opened 2018-02-24 12:07 UTC
## Description
When viewed on a browser, the page appears as horizontally scroll-able, though ideally it shouldn't be so as all the contents fit on one screen.<br>
Browser specifications:
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

## Mocks
When the scrollbar is at extreme left:<br>
![capture](https://user-images.githubusercontent.com/25091775/36630149-cc2d5c9c-1987-11e8-8c31-d695e9132e37.PNG)
When the scrollbar is at extreme right: <br>
![capture2](https://user-images.githubusercontent.com/25091775/36630154-d3eee36a-1987-11e8-96a3-0f093b754d11.PNG)

## Acceptance Criteria
- [ ] The horizontal scroll bar should be removed.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10 minutes

**Comment by sara-02** [comment] 2018-02-24 17:50
@Jap-Leen I am unable to reproduce the error on Mozilla, but I do see a horizontal scroll on Chrome.
Specs
```
Fedora: 27
Mozilla Firefox: Quantum 58.0 (64-bit)
Chrome: Version 64.0.3282.119 (Official Build) (64-bit)
```

**Comment by AnkitKhatri55555** [comment] 2018-02-25 07:38
hey, @Jap-Leen check my pr  at #75

**Comment by MeepyMay** [comment] 2018-02-25 09:25
This is missing the Acceptance Criteria section. Please update and thank you!

**Comment by Jap-Leen** [comment] 2018-03-02 10:26
Hey @MeepyMay I have updated the acceptance criteria! :)
@AnkitKhatri55555 Thanks for your contribution. Actually I was waiting for the approval of the mentors to start working on this issue! Nevertheless :)

**Comment by sara-02** [comment] 2018-03-02 10:53
@Jap-Leen #84 already solves the issue, if you please that more work can be done on it, please leave a comment on the PR.

**Comment by MeepyMay** [comment] 2018-03-12 22:51
@Jap-Leen Feel free to fix this! Thank you for waiting for approval. This is a valid issue.

**Comment by BaaniLeen** [comment] 2018-05-29 05:01
@divyanshu-rawat @ancyp Can we close this issue since it is no longer relevant?

**Closed** 2018-05-30 02:19 UTC
Labels: Difficulty: EASY, Type: Enhancement
