### ISSUE TITLE
Fix overlapping data of programs table in mobile view

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/systers.github.io#112] opened 2018-03-03 12:42 UTC
## Description
As a user
I need reduce font size of table text
so that I can fix data in mobile view

## Mocks
![image](https://user-images.githubusercontent.com/25412153/36934355-40a88be2-1f0e-11e8-9b03-8f8b356b6d8d.png)

## Acceptance Criteria
Mobile view description needs to be added for .internships tag in styles.css
### Update [Required]
- [ ] styles.css

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
20 minutes
@MeepyMay  @Janiceilene  i would like to work on this issue

**Comment by BaaniLeen** [comment] 2018-03-03 14:02
@anumehaagrawal Can you add instructions as to how to replicate the bug? It works fine on safari on iPhone. :)

**Comment by anumehaagrawal** [comment] 2018-03-04 03:44
@BaaniLeen  Check this on firefox , and even the font size of  table heading needs to be reduced ( as viewed in Chrome ) .

**Comment by BaaniLeen** [comment] 2018-03-04 03:58
@anumehaagrawal The issue is because for the td tag in style.css, we have used Overflow:auto, therefore, in case of an overflow, it works fine with Safari as well as chrome, but does not work so with Firefox! :)
A similar problem and its solution has been discussed here! https://stackoverflow.com/questions/16328233/overflow-auto-does-not-work-in-firefox. :)

**Comment by divyanshu-rawat** [comment] 2018-03-06 00:18
@anumehaagrawal I agree with you on this.
Overflow: auto does not work in Firefox 👍

**Comment by BaaniLeen** [comment] 2018-05-30 04:14
Closing it since the issue is not valid in the new codebase. :)

**Closed by BaaniLeen** 2018-05-30 04:14 UTC
Labels: Category: Coding, Type: Bug
