### ISSUE TITLE
The  most common keywords should appear in one or more of the meta-tag-for SEO

### ISSUE THREAD

**Issue by Geekcoder555** [systers/systers.github.io#124] opened 2018-03-04 14:36 UTC
## Description
The  most common keywords should appear in one or more of the meta-tags above. The  primary keywords should appear in the meta-tags to help identify the topic of the  webpage to search engines.

systers
projects 
code 
corps 
source 

Fix:
First of all, you must make sure that the page is using the meta-description tags.
Second, you must adjust these tags content in order to include some of the primary keywords displayed above.
## Acceptance Criteria
you must adjust these tags content in order to include some of the primary keywords displayed above

### Update [Required]
- [ ]  index.html
- [ ] code-of-conduct.html
- [ ] contactus.html
- [ ] member-levels.html
- [ ] newcomers.html
- [ ] open-source-workflow.html
- [ ] reporting-guidelines.html
- [ ] gsoc/2009.html
- [ ]  gsoc/2010.html
- [ ]  gsoc/2011.html
- [ ]  gsoc/2012.html
- [ ] gsoc/2014.html
- [ ] gsoc/2015.html
- [ ] gsoc/2016.html
- [ ]  gsoc/2017.html
- [ ] RGSoC/2018.html
- [ ] Outreachy/2017.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by sara-02** [comment] 2018-03-04 14:41
@AnkitKhatri55555 Is this related to https://github.com/systers/systers.github.io/issues/95? 
Can you update the previous issue instead of opening a new one?

**Comment by AnkitKhatri55555** [comment] 2018-03-04 17:50
@sara-02 ,I think it should be kept as a separate one

**Comment by isunitha98selvan** [comment] 2018-03-05 08:29
I would like to work on this.

**Comment by Saichethan** [comment] 2018-03-06 04:02
@sara-02, @isunitha98selvam I think this is duplicate of #100 PR
Please check!

**Comment by BaaniLeen** [comment] 2018-04-30 04:59
@Geekcoder555 Are you currently working on this issue? If not, @divyanshu-rawat Can I work on this issue since PR #100 has already been closed?

**Comment by divyanshu-rawat** [comment] 2018-04-30 08:01
@Geekcoder555 are u still working on this? else I am assigning @BaaniLeen 👍

**Comment by divyanshu-rawat** [comment] 2018-05-27 08:43
@BaaniLeen would like to work on it?

**Comment by BaaniLeen** [comment] 2018-05-29 04:11
@ancyp @divyanshu-rawat I would like to work it. I feel this can be done throughout the GSoC period or at the end of it, when all our webpages are ready. What are you views upon it?

**Comment by BaaniLeen** [comment] 2018-06-15 03:48
@pprathameshmore Would you like to work on this issue for the current gsoc18-code codebase?

**Comment by Geekcoder555** [comment] 2018-06-15 18:20
Is anyone working on this?

**Comment by BaaniLeen** [comment] 2018-06-24 19:15
@Geekcoder555 No. Can you please update the description wrt the gsoc18-code branch? And then request the @systers/maintainers-gh-pages to assign you the issue if you want to work on it. :)

**Comment by BaaniLeen** [comment] 2018-06-29 01:17
@ancyp Since there is no acknowledgement from @Geekcoder555 , shall we unassign the issue and mark it as available for others?

**Comment by Geekcoder555** [comment] 2018-06-29 07:55
Hey..I am now working on it..was a just busy with an internship.

**Comment by sarnava1** [comment] 2018-10-16 20:28
@BaaniLeen I am claiming this. Please assign me this issue.

**Closed** 2018-12-14 04:07 UTC
Labels: Category: Coding, Difficulty: EASY
