### ISSUE TITLE
Logos of programs

### ISSUE THREAD

**Issue by ancyp** [systers/systers.github.io#121] opened 2018-03-03 17:34 UTC
## Description
As a user of the webpage, it would be nice to have small sized logos of GSoc, Outreachy, RSoC under programs, to the left of their respective year wise links, so that I can get a better user experience.

### Update [Required]
- [ ] index.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
20 minutes

**Comment by Paarmita** [comment] 2018-03-04 14:51
@ancyp Could I take up this?

**Comment by sara-02** [comment] 2018-03-04 15:50
@ancyp @Paarmita this looks like a duplicate of #113.
Also we have a PR https://github.com/systers/systers.github.io/pull/123 for issue #113.
Please check the issue and the PR and close this one if a duplicate.

**Comment by divyanshu-rawat** [comment] 2018-03-05 10:30
@sara-02 You are wrong, I guess this issue is about adding small-sized logos of the programs but issue #123 and issue #113 is all about reducing the size of the social media icons.
Correct me If I am wrong 👍 
Please Look into it again and if this different assign someone on it.

**Comment by sara-02** [comment] 2018-03-05 19:28
@divyanshu-rawat thanks. Yes these are separate issues :)

**Comment by sara-02** [comment] 2018-03-05 19:29
@Paarmita you are free to take this up.

**Comment by divyanshu-rawat** [comment] 2018-03-05 19:40
@Paarmita feel free to take this task 👍

**Comment by Paarmita** [comment] 2018-03-06 06:40
@ancyp Should the logos be added like this or on the heading?
![screenshot from 2018-03-06 12-08-03](https://user-images.githubusercontent.com/26546816/37017630-4ec74954-2137-11e8-99d3-d527e7e85205.png)

**Comment by sara-02** [comment] 2018-03-06 06:42
@Paarmita I think adding them to the heading should be good enough Adding it for each year might get crowded overtime ;)
For Codeathons we are good beacuse different programs have different logos.

**Comment by ancyp** [comment] 2018-03-06 06:54
Thanks @sara-02. Am I allowed to give the task to someone or should I wait for the project managers to assign it? I read so somewhere on slack. Sorry I am new here.

**Comment by sara-02** [comment] 2018-03-06 09:02
Also, @Paarmita has created a PR, PTAL and add your reviews.

**Comment by divyanshu-rawat** [comment] 2018-03-06 09:12
@Paarmita Thanks for the PR 👍

**Closed** 2018-03-16 17:20 UTC
